### ISSUE TITLE
Dual wield ammo bug

### ISSUE THREAD

**Issue by dealw1t** [RedEM-RP/redemrp_inventory#41]
Can you find a solution for ReloadWeapons() function in dual wield modification? I mean the ammunition is transferred to all other weapons. So if you have a revolver with 80 ammo and a revolver with 1 ammo, the 2. revolver also will get 80 ammo if you use it from inventory. You can use this to gain infinite ammunition by swapping weapons. That because redemrp weapon system uses the gunbelt and not the actual ammo clip to save the ammo count. (weapon ammo clip amount is part of gunbelt amount).

**Comment by DeVerino-DVR** [comment]
> Can you find a solution for ReloadWeapons() function in dual wield modification? I mean the ammunition is transferred to all other weapons. So if you have a revolver with 80 ammo and a revolver with 1 ammo, the 2. revolver also will get 80 ammo if you use it from inventory. You can use this to gain infinite ammunition by swapping weapons. That because redemrp weapon system uses the gunbelt and not the actual ammo clip to save the ammo count. (weapon ammo clip amount is part of gunbelt amount).

I had exactly the same problem, I gave up.
